version: "3.9"

services:
  mysql:
    image: "mysql:8.0.11"
    environment:
    #  MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql/password"
    secrets:
      - source: mysql
        target: mysql/password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
    configs:
      - source: chat_init
        target: /docker-entrypoint-initdb.d/chat.sql
    networks:
      - demonet

  chat:
    image: "registry.gitlab.com/etrs712/exemple_chat/chat:master"
    build:             
      context: php
      dockerfile: Dockerfile
    secrets:
      - source: mysql
        target: mysql/password
    ports:
      - 9000:80
    networks:
      - demonet
    depends_on:
      - mysql

networks:
  demonet:

secrets:
  mysql:
    file: ./passwd

configs:
  chat_init:
    file: ./chat.mysql
