apiVersion: v1
kind: Service
metadata:
  name: chat
  labels:
    app: flaskr
    role: front
spec:
  selector:
    app: flaskr
    role: front
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32123
    loadBalancerIP: 10.0.2.15

