apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: flaskr
    role: front
spec:
  selector:
    matchLabels:
      app: flaskr
      role: front
  template:
    metadata:
      labels:
        app: flaskr
        role: front
    spec:
      containers:
      - name: chat
        image: registry.gitlab.com/etrs712/exemple_chat/chat:v1.0.1
        ports:
          - containerPort: 80
            name: http
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "0.3"
        volumeMounts:
          - name: mysql-password
            mountPath: "/var/run/secrets/mysql/"
      volumes:
        - name: mysql-password
          secret:
            secretName: mysql-secret
            items:
              - key: password
                path: password
