apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-chat-pvc
  labels:
    app: flaskr
    role: db
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
