apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-srv
  labels:
    app: nginx
    role: front
spec:
  selector:
    matchLabels:
      app: nginx
      role: front
  template:
    metadata:
      labels:
        app: nginx
        role: front
    spec:
      containers:
      - name: web-srv
        image: registry.gitlab.com/etrs712/exemple_chat/chat:v1.0.1
        ports:
          - containerPort: 80
            name: http
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
          requests:
            memory: "200Mi"
            cpu: "0.3"